version: "3.6"

volumes:
  redis-playground-prometheus_prometheus:
  redis-playground-prometheus_grafana:

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
     - redis-playground

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter
    ports:
      - 9121:9121
    environment:
      - REDIS_ADDR=redis://redis:6379
    networks:
     - redis-playground
    depends_on:
     - redis

  redis-playground-api:
    container_name: redis-playground-api
    ports:
     - 5000:80
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: src/Redis.Playground.App/backend
      dockerfile: Redis.Playground.Api.Dockerfile
    networks:
     - redis-playground
    depends_on:
     - redis

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.22
    ports:
     - 5775:5775/udp
     - 6831:6831/udp
     - 6832:6832/udp
     - 5778:5778
     - 16686:16686
     - 14268:14268
     - 14250:14250
     - 9411:9411
    environment:
     - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
     - redis-playground

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - redis-playground-prometheus_prometheus:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - redis-playground

  docker-exporter:
    container_name: docker-exporter
    image: prometheusnet/docker_exporter:latest
    ports:
     - "9417:9417"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - redis-playground

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - redis-playground
    volumes:
      - redis-playground-prometheus_grafana:/var/lib/grafana
      - ./grafana/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana/datasources/datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yaml
      - ./grafana/dashboards:/dashboards
    environment:
      # https://grafana.com/plugins/flant-statusmap-panel
      # https://grafana.com/plugins/grafana-piechart-panel
      # https://grafana.com/plugins/grafana-polystat-panel
      # https://grafana.com/plugins/jdbranham-diagram-panel
      # https://grafana.com/plugins/michaeldmoore-multistat-panel
      # https://grafana.com/plugins/vonage-status-panel
      # https://grafana.com/plugins/yesoreyeram-boomtable-panel
      GF_INSTALL_PLUGINS: "flant-statusmap-panel,grafana-piechart-panel"

networks:
  redis-playground:
